# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://broadwater.io
title: broadwater.io
email: david@broadwater.io
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: resume
    icon: briefcase
    url: http://broadwater.io/resume/
  - title: linkedin
    icon: linkedin
    url: https://www.linkedin.com/in/davidbroadwater
  - title: github
    icon: github
    url: https://github.com/davidbroadwater