# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://broadwater.io
title: broadwater.io
email: david@broadwater.io
description: Personal website and portfolio for David J. Broadwater. David is a top performing scientist and military veteran with 7 years of experience and a fascination with finding meaning in data, as well as a skilled communicator with an advanced technical degree and management perspective.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: resume
    icon: briefcase
    url: http://broadwater.io/resume/
  - title: linkedin
    icon: linkedin
    url: https://www.linkedin.com/in/davidbroadwater
  - title: github
    icon: github
    url: https://github.com/davidbroadwater