# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://broadwater.io
title: broadwater.io
email: info@broadwater.io
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 
